# Generated by Django 2.2.3 on 2021-04-27 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20, null=True)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('bloqueado', models.BooleanField(default=False)),
                ('clave', models.CharField(default='1234', max_length=16)),
                ('dia', models.CharField(blank=True, default='', max_length=2, null=True)),
                ('mes', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('anio', models.CharField(blank=True, default='', max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.CharField(default='no', max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos')),
                ('masVisto', models.BooleanField(default=False)),
                ('intro', models.BooleanField(default=False)),
                ('titulo', models.CharField(default='', max_length=100)),
                ('subtitulo', models.CharField(default='', max_length=100, null=True)),
                ('click', models.CharField(default=0, max_length=100, null=True)),
                ('cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a.Categorias')),
            ],
        ),
    ]
